theme: jekyll-theme-minimal
logo: /assets/img/logo.jpg
plugins:
  - jekyll-redirect-from
title:
  de: Willkommen! :)
  en: Welcome! :)
about:
  de: Über Uns
  en: About Us
computer:
  de: Informatik
  en: Computer Science
cosplay:
  de: Cosplay
  en: Cosplay