theme: jekyll-theme-minimal
logo: /assets/img/logo.jpg
plugins:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
languages: ["en", "de"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  de: Deutsch
  en: English