# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Welcome! :)
  de: Willkommen! :)
email: kevnana@gmx.de
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  de: Dies ist eine unglaublich coole Beschreibung der Seite auf deutsch.
index:
  en: nanakev-en.html
  de:
feed:
  en: /feed.xml
  de: /flux.xml
url: "http://nanakev.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  nanakev

# Build settings
markdown: kramdown
