# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Nana & Kev's Awesome Homepage
  de: Nana & Kev's Unglaubliche Homepage
email: kevnana@gmx.de
description:
  en: A little homepage from Nana & Kev.
  de: Eine kleine Homepage von Nana & Kev.
index:
  en: en/index
  de:
url: "http://nanakev.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  nanakev
plugins:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
